grafana:
  enabled: true
  adminPassword: admin
  
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards

  dashboards:
    default:
      app-metrics:
        json: |
          {
            "annotations": {
              "list": []
            },
            "editable": true,
            "gnetId": null,
            "graphTooltip": 0,
            "hideControls": false,
            "links": [],
            "refresh": "10s",
            "rows": [
              {
                "collapse": false,
                "height": "250px",
                "panels": [
                  {
                    "aliasColors": {},
                    "bars": false,
                    "datasource": null,
                    "fill": 1,
                    "id": 1,
                    "legend": {
                      "avg": false,
                      "current": false,
                      "max": false,
                      "min": false,
                      "show": true,
                      "total": false,
                      "values": false
                    },
                    "lines": true,
                    "linewidth": 1,
                    "links": [],
                    "nullPointMode": "null",
                    "percentage": false,
                    "pointradius": 5,
                    "points": false,
                    "renderer": "flot",
                    "seriesOverrides": [],
                    "span": 12,
                    "stack": false,
                    "steppedLine": false,
                    "targets": [
                      {
                        "expr": "rate(http_requests_total[5m])",
                        "interval": "",
                        "legendFormat": "{{handler}}",
                        "refId": "A"
                      }
                    ],
                    "thresholds": [],
                    "timeFrom": null,
                    "timeShift": null,
                    "title": "Request Rate",
                    "tooltip": {
                      "shared": true,
                      "sort": 0,
                      "value_type": "individual"
                    },
                    "type": "graph",
                    "xaxis": {
                      "mode": "time",
                      "name": null,
                      "show": true,
                      "values": []
                    },
                    "yaxes": [
                      {
                        "format": "short",
                        "label": null,
                        "logBase": 1,
                        "max": null,
                        "min": null,
                        "show": true
                      },
                      {
                        "format": "short",
                        "label": null,
                        "logBase": 1,
                        "max": null,
                        "min": null,
                        "show": true
                      }
                    ]
                  }
                ]
              },
              {
                "collapse": false,
                "height": 250,
                "panels": [
                  {
                    "aliasColors": {},
                    "bars": false,
                    "datasource": null,
                    "fill": 1,
                    "id": 2,
                    "legend": {
                      "avg": false,
                      "current": false,
                      "max": false,
                      "min": false,
                      "show": true,
                      "total": false,
                      "values": false
                    },
                    "lines": true,
                    "linewidth": 1,
                    "links": [],
                    "nullPointMode": "null",
                    "percentage": false,
                    "pointradius": 5,
                    "points": false,
                    "renderer": "flot",
                    "seriesOverrides": [],
                    "span": 12,
                    "stack": false,
                    "steppedLine": false,
                    "targets": [
                      {
                        "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
                        "interval": "",
                        "legendFormat": "{{handler}}",
                        "refId": "A"
                      }
                    ],
                    "thresholds": [],
                    "timeFrom": null,
                    "timeShift": null,
                    "title": "Average Response Time",
                    "tooltip": {
                      "shared": true,
                      "sort": 0,
                      "value_type": "individual"
                    },
                    "type": "graph",
                    "xaxis": {
                      "mode": "time",
                      "name": null,
                      "show": true,
                      "values": []
                    },
                    "yaxes": [
                      {
                        "format": "s",
                        "label": null,
                        "logBase": 1,
                        "max": null,
                        "min": null,
                        "show": true
                      },
                      {
                        "format": "short",
                        "label": null,
                        "logBase": 1,
                        "max": null,
                        "min": null,
                        "show": true
                      }
                    ]
                  }
                ]
              }
            ],
            "schemaVersion": 14,
            "style": "dark",
            "timezone": "browser",
            "title": "Application Metrics",
            "version": 0
          }

  persistence:
    type: pvc
    enabled: true
    size: 10Gi

  service:
    type: LoadBalancer

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL