prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    additionalScrapeConfigs:
      - job_name: 'webapp'
        metrics_path: /metrics
        static_configs:
          - targets: ['webapp.default.svc.cluster.local']
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
        - match:
            alertname: Watchdog
          receiver: 'null'
    receivers:
      - name: 'null'

# ServiceMonitor para la aplicación
serviceMonitor:
  enabled: true
  selector:
    matchLabels:
      app: webapp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s