kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres  # Este es el valor por defecto de Bitnami PostgreSQL
  POSTGRES_PASSWORD: postgres  # Asegúrate de que coincida con la contraseña que configuraste
EOF