apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres  # El nombre de usuario de PostgreSQL
  POSTGRES_PASSWORD: Aw6d9bUftI  # La contraseña de PostgreSQL
